// Harness 0.2.0-rc.2 typography/radius/elevation tokens are inherited live.
// Shared Input and Button own control typography, borders, focus and dimensions.
// Conversation text uses the same host font-size preference as the main composer.
export const styles = `
.cwn{position:relative;--cwn-accent:var(--dsw-alias-state-business-primary);--cwn-muted:var(--dsw-alias-label-tertiary);--cwn-border:var(--dsw-alias-border-l3);display:flex;flex-direction:column;height:100%;min-height:0;overflow:hidden;color:var(--dsw-alias-label-primary);font-family:inherit;font-size:var(--dsw-font-s-14-font-size);line-height:var(--dsw-font-s-14-line-height);container-type:inline-size}
.cwn *{box-sizing:border-box}.cwn svg{flex-shrink:0}.cwn select,.cwn textarea{font-family:inherit}.cwn-worker,.cwn-cli-heading{font:inherit}.cwn button{cursor:pointer}.cwn button:disabled{cursor:default;opacity:.45}.cwn button:focus-visible,.cwn summary:focus-visible,.cwn input:focus-visible,.cwn textarea:focus-visible,.cwn select:focus-visible{outline:2px solid var(--cwn-accent);outline-offset:2px}
.cwn-brand{display:inline-flex;position:relative;flex-shrink:0;vertical-align:middle}.cwn-brand img{display:block;width:100%;height:100%;object-fit:contain}.cwn-brand .cwn-icon-dark{display:none}body[data-ds-dark-theme] .cwn-brand .cwn-icon-light{display:none}body[data-ds-dark-theme] .cwn-brand .cwn-icon-dark{display:block}
.cwn-head{display:flex;align-items:center;gap:9px;min-height:54px;padding:12px 16px;flex-shrink:0;border-bottom:.5px solid var(--dsw-alias-border-l2)}.cwn-head h2{flex:1;min-width:0;font-size:var(--dsw-font-s-14-font-size);line-height:var(--dsw-font-s-14-line-height);font-weight:600;margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cwn-back,.cwn-settings-button{width:28px!important;padding:0!important;flex-shrink:0}.cwn-back{border-radius:var(--dsw-radius-md)!important;background:var(--dsw-alias-interactive-bg-hover)!important}
.cwn-overview{flex:1;overflow:auto;min-height:0;padding:14px 14px 20px;overscroll-behavior:contain}.cwn-search{width:100%}

.cwn-filters{display:flex;gap:6px;margin:10px 0 14px}.cwn-filters button{flex:1;min-width:0;padding:0 7px;background:var(--dsw-alias-interactive-bg-hover)!important}.cwn-filters button[aria-pressed=true]{color:var(--cwn-accent)!important;border-color:var(--cwn-border)!important;background:color-mix(in srgb,var(--cwn-accent) 10%,transparent)!important}.cwn-filter-info{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:var(--dsw-font-xxs-12-font-size);color:var(--cwn-muted);margin:0 0 10px}
.cwn-cli-group{border:.5px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-lg);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 65%,var(--dsw-alias-interactive-bg-hover));margin:0 0 12px;overflow:hidden}.cwn-cli-heading{display:flex;align-items:center;gap:9px;width:100%;min-height:45px;padding:10px 12px;border:0;background:transparent;color:inherit;text-align:left}.cwn-cli-heading strong{font-size:var(--dsw-font-s-14-font-size);font-weight:600;flex:1;min-width:0}.cwn-cli-heading>span:not(.cwn-brand){font-size:var(--dsw-font-xxs-12-font-size);color:var(--cwn-muted);white-space:nowrap}.cwn-cli-heading>svg{width:12px;height:12px;color:var(--cwn-muted);transform:rotate(90deg)}.cwn-cli-heading[aria-expanded=false]>svg{transform:none}.cwn-cli-heading[aria-expanded=true]{border-bottom:.5px solid var(--dsw-alias-border-l2)}
.cwn-worker{display:flex;width:100%;align-items:center;gap:10px;padding:12px;background:transparent;color:inherit;border:0;text-align:left;min-height:62px;position:relative}.cwn-worker+.cwn-worker:before{content:'';position:absolute;left:12px;right:12px;top:0;height:.5px;background:var(--dsw-alias-border-l2)}.cwn-worker:hover,.cwn-worker:focus-visible{background:color-mix(in srgb,var(--cwn-accent) 9%,transparent)}.cwn-worker>svg{width:14px;height:14px;color:var(--cwn-muted)}.cwn-worker-content{flex:1;min-width:0}.cwn-worker-line{display:flex;align-items:center;gap:8px;min-width:0}.cwn-worker-title{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:var(--dsw-font-s-14-font-size);font-weight:500}.cwn-worker-status{display:inline-flex;align-items:center;gap:5px;font-size:var(--dsw-font-xxs-12-font-size);white-space:nowrap;flex-shrink:0;color:var(--cwn-muted)}.cwn-dot{display:inline-block;flex-shrink:0;width:6px;height:6px;border-radius:50%;background:var(--dsw-alias-state-idle-primary)}.cwn-worker-status.running{color:var(--cwn-accent)}.cwn-dot.running{background:var(--cwn-accent)}.cwn-worker-status.completed{color:var(--dsw-alias-state-success-primary)}.cwn-dot.completed{background:var(--dsw-alias-state-success-primary)}.cwn-worker-status.failed{color:var(--dsw-alias-state-error-primary)}.cwn-dot.failed{background:var(--dsw-alias-state-error-primary)}.cwn-worker-status.queued,.cwn-worker-status.stopping{color:var(--dsw-alias-state-warn-label)}.cwn-dot.queued,.cwn-dot.stopping{background:var(--dsw-alias-state-warn-primary)}.cwn-worker-meta{display:flex;align-items:center;gap:7px;margin-top:5px;color:var(--cwn-muted);font-size:var(--dsw-font-xxs-12-font-size);min-width:0}.cwn-worker-meta>span:first-child{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cwn-worker-meta>span:last-child{flex-shrink:0;white-space:nowrap}.cwn-meta-divider{opacity:.5}
.cwn-actions{position:relative}.cwn-actions>summary{display:flex;width:28px;height:28px;align-items:center;justify-content:center;list-style:none;border-radius:var(--dsw-radius-md);cursor:pointer}.cwn-actions>summary::-webkit-details-marker{display:none}.cwn-actions>summary:hover{background:var(--dsw-alias-interactive-bg-hover)}.cwn-action-menu{position:absolute;right:0;top:34px;width:240px;max-width:calc(100cqw - 32px);z-index:5;padding:12px;background:var(--dsw-alias-bg-layer-1);border:.5px solid var(--cwn-border);border-radius:var(--dsw-radius-lg);--dsw-elevation-stroke-color:var(--dsw-alias-border-l2);box-shadow:var(--dsw-elevation-panel);font-size:var(--dsw-font-xxs-12-font-size);overflow-wrap:anywhere}.cwn-action-menu p{color:var(--cwn-muted);margin:8px 0;font-size:var(--dsw-font-xxs-12-font-size)}.cwn-action-menu>button{display:flex;margin-top:8px}
.cwn-feed{flex:1;overflow:auto;overscroll-behavior:contain;min-height:60px;padding:18px 16px}.cwn-message{width:100%;margin:0 0 22px}.cwn-message.user{width:fit-content;max-width:85%;margin-left:auto}.cwn-message.user .cwn-text{padding:10px 12px;border-radius:var(--dsw-radius-lg);background:var(--dsw-specific-bubble,var(--dsw-alias-interactive-bg-hover))}.cwn-message-label{position:relative;display:flex;justify-content:flex-end;color:var(--cwn-muted);font-size:var(--dsw-font-xxs-12-font-size);margin-bottom:6px}.cwn-message.assistant .cwn-message-label{justify-content:flex-start}.cwn-text{white-space:pre-wrap;overflow-wrap:anywhere;line-height:calc(24px + var(--dsh-content-font-delta,0px));font-size:var(--dsh-content-font-size,14px)}.cwn-tool{border:.5px solid var(--dsw-alias-border-l2);border-radius:var(--dsw-radius-md);margin:8px 0;background:var(--dsw-alias-interactive-bg-hover);font-size:var(--dsw-font-xxs-12-font-size)}.cwn-tool summary{display:flex;align-items:center;gap:7px;padding:10px;cursor:pointer;list-style:none}.cwn-tool summary::-webkit-details-marker{display:none}.cwn-tool summary:before{content:'›';color:var(--cwn-muted)}.cwn-tool[open] summary:before{transform:rotate(90deg)}.cwn-tool-title{min-width:0;flex:1;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.cwn-tool small{font-size:var(--dsw-font-xxs-12-font-size);color:var(--cwn-muted);max-width:38%;overflow-wrap:anywhere}.cwn-tool pre{white-space:pre-wrap;overflow-wrap:anywhere;font:var(--dsw-font-xxs-12-font-size)/1.6 var(--ds-font-family-code,monospace);margin:0;padding:0 12px 12px;max-height:320px;overflow:auto}.cwn-status{font-size:var(--dsw-font-xxs-12-font-size);color:var(--cwn-muted);text-align:center;margin:16px 0}
.cwn-compose{padding:8px 12px 12px;flex-shrink:0}.cwn-compose-state{display:flex;align-items:center;gap:6px;font-size:var(--dsw-font-xxs-12-font-size);color:var(--cwn-muted);margin:0 4px 7px}.cwn-compose-box{padding:10px;border:0;border-radius:var(--dsw-radius-panel);--dsw-elevation-stroke-color:var(--dsw-alias-border-l2);box-shadow:var(--dsw-elevation-soft);background:var(--dsw-specific-input-major,var(--dsw-alias-interactive-bg-hover))}.cwn .cwn-compose textarea:focus-visible{outline:none}.cwn-compose textarea{display:block;width:100%;height:45px;min-height:45px;max-height:140px;resize:vertical;border:0;padding:0 2px;background:transparent;color:inherit;line-height:calc(24px + var(--dsh-content-font-delta,0px));font-size:var(--dsh-content-font-size,14px);outline:none}.cwn-compose textarea::placeholder{color:var(--cwn-muted)}.cwn-compose textarea:disabled{opacity:.6}.cwn-compose-bottom{display:flex;align-items:center;gap:8px;margin-top:6px;min-height:30px}.cwn-compose-model{margin-left:auto;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--cwn-muted);font-size:var(--dsw-font-xxs-12-font-size)}.cwn-send{width:30px!important;height:30px!important;padding:0!important;border-radius:50%!important;flex-shrink:0}.cwn-resume-hint{font-size:var(--dsw-font-xxs-12-font-size);line-height:1.6;color:var(--cwn-muted);margin:0 4px 8px}
.cwn-settings{padding:12px 16px;display:grid;gap:9px;overflow:auto;max-height:65%;flex-shrink:0;border-bottom:.5px solid var(--cwn-border)}.cwn-settings label{font-size:var(--dsw-font-xxs-12-font-size);display:grid;gap:5px}.cwn-settings select{width:100%;border:.5px solid var(--cwn-border);border-radius:var(--dsw-radius-md);background:var(--dsw-alias-bg-layer-1);color:inherit;padding:7px;font-size:var(--dsw-font-s-14-font-size)}.cwn-settings p{font-size:var(--dsw-font-xxs-12-font-size);color:var(--cwn-muted);line-height:1.6;margin:0}
.cwn-empty{padding:30px 10px;text-align:center;color:var(--cwn-muted);line-height:1.8}.cwn-empty h3{color:var(--dsw-alias-label-primary);font-weight:500;font-size:var(--dsw-font-s-14-font-size);margin:12px 0}.cwn-empty p{font-size:var(--dsw-font-xxs-12-font-size)}.cwn-empty blockquote{margin:12px 0;padding:12px;border-radius:var(--dsw-radius-lg);background:var(--dsw-alias-interactive-bg-hover);font-size:var(--dsw-font-xxs-12-font-size);text-align:left}.cwn-notice,.cwn-error{font-size:var(--dsw-font-xxs-12-font-size);padding:12px;border-radius:var(--dsw-radius-md);background:var(--dsw-alias-interactive-bg-hover);line-height:1.6;overflow-wrap:anywhere;margin:8px 12px;max-height:180px;overflow:auto;flex-shrink:0}.cwn-error{color:var(--dsw-alias-state-error-primary)}.cwn-error button{margin:8px 0}.cwn-error details{font-size:var(--dsw-font-xxs-12-font-size)}.cwn-error summary{cursor:pointer}
.cwn-history-nav{border-bottom:.5px solid var(--cwn-border);padding:10px 16px;font-size:var(--dsw-font-xxs-12-font-size);flex-shrink:0}.cwn-history-nav>div{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.cwn-history-nav small{color:var(--cwn-muted)}.cwn-history-start{display:flex;align-items:center;flex-wrap:wrap;justify-content:space-between;gap:8px;font-size:var(--dsw-font-xxs-12-font-size);margin:0 0 16px;color:var(--cwn-muted)}.cwn-jump{display:flex;justify-content:center;padding:4px 12px 8px}.cwn-copy{display:inline-flex;align-items:center;gap:6px;margin-top:5px;max-width:100%}.cwn-copy button{color:var(--cwn-muted)}.cwn-copy-feedback{font-size:var(--dsw-font-xxs-12-font-size);overflow-wrap:anywhere;color:var(--cwn-muted)}.cwn-sr-only{position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
@container (max-width:320px){.cwn-head{padding:10px 12px}.cwn-overview{padding:10px}.cwn-worker-line{gap:5px}.cwn-worker-status{font-size:var(--dsw-font-xxs-12-font-size)}.cwn-worker-meta{gap:5px}.cwn-filters{gap:4px}.cwn-filters button{padding:0 4px!important}.cwn-feed{padding:14px 12px}}
`

// Geometry below mirrors Harness 0.2.0-rc.2 chat/composer and sidebar New Session.
export const nativeChatStyles = `
.cwn-entry{width:32px;height:32px;min-width:32px;padding:2px!important;flex-shrink:0;background:transparent!important;border:0!important;box-shadow:none!important}
.cwn-entry:hover{background:var(--dsw-alias-interactive-bg-hover)!important}
.cwn .cwn-search{height:38px;border-color:var(--dsw-alias-border-l3);background:var(--dsw-alias-bg-base)}
.cwn .cwn-search:focus-within{outline:none;box-shadow:none;border-color:var(--dsw-alias-border-l3)}
.cwn .cwn-search input:focus-visible{outline:none;box-shadow:none}
.cwn .cwn-search input::placeholder{color:var(--dsw-alias-label-caption)}
.cwn-cli-group,.cwn-back,.cwn-settings select,.cwn-tool{border:.5px solid var(--dsw-alias-border-l3)}
.cwn-cli-group{background:var(--dsw-alias-button-elevated-fill)}
body[data-ds-dark-theme] .cwn-cli-group{background:var(--dsw-alias-interactive-bg-hover)}
.cwn-feed{padding:16px 24px}
.cwn-message{margin-bottom:24px}
.cwn-message.user{max-width:82%}
.cwn-message.user .cwn-text{padding:10px 16px;border-radius:var(--dsw-radius-xl);line-height:calc(22px + var(--dsh-content-font-delta,0px))}
.cwn-message-label{height:28px;margin:6px 0 0;gap:8px;align-items:center;font-size:var(--dsh-content-font-size-secondary,13px);line-height:24px}
.cwn-message.assistant .cwn-message-label{margin-top:16px;margin-left:-6px}
.cwn-markdown{min-width:0;overflow-wrap:anywhere}
.cwn-copy{margin:0;position:relative}
.cwn-copy .cwn-copy-icon{width:28px;height:28px;padding:6px;color:var(--dsw-alias-label-tertiary)}
.cwn-status{text-align:left;border-bottom:.5px solid var(--dsw-alias-border-l2);padding:8px 0;margin:8px 0 16px;font-size:var(--dsh-content-font-size-secondary,13px)}
.cwn-compose{padding:0 16px 4px}
.cwn-compose-box{display:flex;flex-direction:column;gap:12px;padding:8px 0 0}
.cwn-compose textarea{resize:none;height:36px;min-height:36px;max-height:336px;padding:4px 12px 0 14px;overflow-y:auto;margin:0;box-sizing:border-box}
.cwn-compose textarea::placeholder{color:var(--dsw-alias-label-caption)}
.cwn-compose-bottom{justify-content:flex-end;gap:8px;padding:2px 8px 6px;margin:0;min-height:42px}
.cwn-model-menu{margin-left:auto;min-width:0;max-width:calc(100% - 42px)}
.cwn .cwn-compose-model{display:flex;align-items:center;gap:6px;height:28px;max-width:100%;padding:0 8px;font-size:var(--dsh-content-font-size-secondary,13px);line-height:20px;color:var(--dsw-alias-label-secondary);border-radius:var(--dsw-radius-sm)}
.cwn-compose-model>span:first-child{min-width:0;overflow:hidden;text-overflow:ellipsis}
.cwn-model-effort{flex-shrink:0;color:var(--dsw-alias-label-tertiary)}
.cwn .cwn-send{corner-shape:round!important;width:34px!important;height:34px!important;border:0!important;border-radius:999px!important;background:var(--dsw-alias-button-info-fill)!important;color:#fff!important;display:grid;place-items:center;transform:translateY(-2px)}
.cwn .cwn-send:hover:not(:disabled){background:var(--dsw-alias-button-info-hover)!important}
.cwn .cwn-send:disabled{opacity:.4}
.cwn-compose-state{height:24px;gap:8px;margin:4px 8px 0;font-size:var(--dsh-content-font-size-secondary,13px);line-height:20px}
.cwn-compose-cli{margin-left:auto}
@container(max-width:320px){.cwn-feed{padding:14px 16px}.cwn-compose{padding-left:8px;padding-right:8px}.cwn-model-effort{display:none}}
`

export const modelPickerStyles = `
.cwn-progress{margin:12px 0 16px;padding-bottom:12px;border-bottom:.5px solid var(--dsw-alias-border-l2);color:var(--dsw-alias-label-tertiary);font-size:var(--dsh-content-font-size,14px);line-height:22px}
.cwn-progress>summary{display:flex;gap:6px;align-items:center;cursor:pointer;list-style:none}.cwn-progress>summary::-webkit-details-marker{display:none}.cwn-progress-chevron{display:inline-flex;transform:rotate(90deg)}.cwn-progress-chevron svg{width:12px;height:12px}.cwn-progress[open] .cwn-progress-chevron{transform:rotate(-90deg)}
.cwn-process-body{padding-top:12px;display:grid;gap:8px}.cwn-process-note{margin:0;font-size:var(--dsh-content-font-size-secondary,13px);color:var(--dsw-alias-label-tertiary)}.cwn-process-event{font-size:var(--dsh-content-font-size-secondary,13px)}

.cwn-model-popover{width:max-content;min-width:min(240px,calc(100vw - 32px));max-width:min(420px,calc(100vw - 32px));max-height:min(360px,calc(100vh - 96px));padding:4px;color:var(--dsw-alias-label-primary);--dsw-elevation-stroke-color:var(--dsw-alias-border-l1);box-shadow:var(--dsw-elevation-prominent)}
.cwn-model-popover button[role=menuitem]{min-height:34px;padding:5px 7px;font-size:13px;font-weight:400;line-height:20px;border-radius:var(--dsw-radius-md)}
.cwn-model-cell{display:flex;align-items:center;gap:6px;width:100%;min-width:0}.cwn-model-cell>span:first-child{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cwn-model-cell-value{color:var(--dsw-alias-label-tertiary);text-align:right;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:230px}
.cwn-model-search{background:transparent!important;border:0!important;box-shadow:none!important;padding:5px 7px!important;margin:2px 0 3px;height:auto!important}.cwn-model-search input{font-size:12px!important;padding:0!important}.cwn-model-provider,.cwn-model-feedback{font-size:12px;line-height:18px;color:var(--dsw-alias-label-tertiary);padding:8px}.cwn-model-feedback{max-width:280px;white-space:normal}
/* Scope to plugin buttons, including the portaled menu and header entry. */
.cwn button,.cwn-entry,.cwn-model-popover button{border:0!important;--dsw-elevation-stroke-color:transparent;box-shadow:none}
.cwn-cli-heading{position:relative}.cwn-cli-heading[aria-expanded=true]:after{content:'';position:absolute;bottom:0;left:0;right:0;height:.5px;background:var(--dsw-alias-border-l2);pointer-events:none}
.cwn-back:hover:not(:disabled),.cwn-filters button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover-solid)!important}
.cwn-filters button[aria-pressed=true]:hover:not(:disabled){background:color-mix(in srgb,var(--cwn-accent) 18%,transparent)!important}
.cwn-cli-heading:hover:not(:disabled),.cwn-model-popover button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}
.cwn button:focus-visible,.cwn-entry:focus-visible,.cwn-model-popover button:focus-visible{outline:2px solid var(--dsw-alias-state-business-primary);outline-offset:2px}
@media(prefers-reduced-motion:reduce){.cwn button,.cwn-entry,.cwn-model-popover button{transition:none}}

.cwn .cwn-send{padding:0;min-width:34px;min-height:34px;flex:none}.cwn .cwn-send svg{width:16px;height:16px}
`

export const telemetryStyles = `
.cwn-stat{display:inline-flex;align-items:center;gap:6px;border-radius:var(--dsw-radius-sm);color:var(--dsw-alias-label-tertiary);font-size:var(--dsh-content-font-size-secondary,13px);line-height:calc(20px + var(--dsh-content-font-delta-secondary,0px));font-variant-numeric:tabular-nums;white-space:nowrap;padding:1px 8px;min-width:0;transition:background-color 180ms ease,color 180ms ease}
.cwn-stat>span{overflow:hidden;text-overflow:ellipsis}.cwn-stat:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary)}
.cwn-message-label time{white-space:nowrap;flex-shrink:0}.cwn-message-label .cwn-usage{padding-left:0}.cwn-message-label{gap:6px}
.cwn-telemetry{margin:4px 0 0;gap:0;justify-content:space-between}.cwn-telemetry .cwn-usage{flex:1;justify-content:center}.cwn-run-stat{max-width:35%}.cwn-context{flex-shrink:0}
.cwn-context-track{fill:none;stroke:var(--dsw-alias-border-l3);stroke-width:2}.cwn-context-fill{fill:none;stroke:var(--dsw-alias-label-tertiary);stroke-width:2;stroke-linecap:round}



@media(prefers-reduced-motion:reduce){.cwn-stat,.cwn summary{transition:none}}
@container(max-width:360px){.cwn-message-label{flex-wrap:wrap;height:auto;min-height:28px}.cwn-message-label time{margin-left:0}.cwn-telemetry .cwn-stat{padding-left:4px;padding-right:4px;gap:4px}}
`

// Pinned to Harness 0.2.0-rc.2: WorkStatus, MessageIconActions, StatsPills,
// TurnUsagePanel, ContextMeter and ModelSelect. Native Tooltip/Menu own animations.
export const nativeInteractionStyles = `
.cwn-progress{padding-bottom:0;border:0}.cwn-progress>summary{height:calc(33px + var(--dsh-content-font-delta,0px));width:100%;padding:0 0 8px;border-radius:0;border-bottom:.5px solid var(--dsw-alias-border-l2);transition:color .1s;line-height:calc(24px + var(--dsh-content-font-delta,0px));gap:4px}.cwn-progress>summary:hover{color:var(--dsw-alias-label-secondary);background:transparent}.cwn-progress-chevron{transition:transform .1s}.cwn-progress-chevron svg{width:14px;height:14px}
.cwn-message-label{height:calc(28px + var(--dsh-content-font-delta,0px));gap:8px}.cwn-message-label time{line-height:calc(24px + var(--dsh-content-font-delta,0px))}.cwn-message.assistant .cwn-message-label time{font-size:calc(var(--dsh-content-font-size-secondary,13px) - 1px)}
.cwn-copy .cwn-copy-icon{width:calc(28px + var(--dsh-content-font-delta,0px));height:calc(28px + var(--dsh-content-font-delta,0px));padding:6px;border-radius:var(--dsw-radius-sm);color:var(--dsw-alias-label-tertiary)}.cwn-copy-icon svg{width:calc(15px + var(--dsh-content-font-delta,0px));height:calc(15px + var(--dsh-content-font-delta,0px))}.cwn-message.assistant .cwn-copy-icon svg{width:calc(17px + var(--dsh-content-font-delta,0px));height:calc(17px + var(--dsh-content-font-delta,0px))}.cwn-copy .cwn-copy-icon:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary)}
.cwn-stat-anchor{min-width:0;display:inline-flex}.cwn-telemetry{gap:0;font-size:calc(var(--dsh-content-font-size-secondary,13px) - 1px);line-height:calc(20px + var(--dsh-content-font-delta-secondary,0px))}.cwn-telemetry>.cwn-stat-anchor:nth-child(2){flex:1;justify-content:center}
.cwn-stat{font:inherit;line-height:inherit;transition:none}.cwn-stat:hover{background:transparent;color:var(--dsw-alias-label-tertiary)}.cwn button.cwn-stat{background:transparent;cursor:pointer}.cwn button.cwn-stat:hover,.cwn button.cwn-stat[aria-expanded=true]{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary)}
.cwn-telemetry .cwn-usage{border-radius:999px;corner-shape:round;padding:1px 8px;gap:6px}.cwn-message-label .cwn-stat-anchor{margin-left:8px}.cwn-message-label .cwn-reply-usage{height:calc(28px + var(--dsh-content-font-delta,0px));font-size:calc(var(--dsh-content-font-size-secondary,13px) - 1px);line-height:calc(24px + var(--dsh-content-font-delta,0px));border-radius:var(--dsw-radius-sm);padding:6px 8px;gap:4px}.cwn-reply-usage svg{width:calc(15px + var(--dsh-content-font-delta,0px));height:calc(15px + var(--dsh-content-font-delta,0px))}.cwn button.cwn-reply-usage:hover,.cwn button.cwn-reply-usage[aria-expanded=true]{color:var(--dsw-alias-label-tertiary)}
.cwn-context{border-radius:var(--dsw-radius-sm);font-size:var(--dsh-content-font-size-secondary,13px);line-height:calc(20px + var(--dsh-content-font-delta-secondary,0px));padding:1px 8px;gap:6px}
.cwn-stat-panel{z-index:1100;box-sizing:border-box;border-radius:var(--dsw-radius-lg);background:var(--dsw-specific-menu);width:max-content;min-width:min(300px,100vw - 24px);max-width:min(440px,100vw - 24px);backdrop-filter:var(--dsw-menu-backdrop-filter);--dsw-elevation-stroke-color:var(--dsw-alias-border-l1);box-shadow:var(--dsw-elevation-prominent);color:var(--dsw-alias-label-secondary);cursor:default;border:0;padding:16px;font-size:12px;line-height:18px;position:fixed}
.cwn-stat-title{color:var(--dsw-alias-label-primary);display:flex;justify-content:space-between;gap:16px;margin-bottom:8px;font-weight:500}.cwn-stat-title>span{display:inline-flex;align-items:center;gap:6px;font-variant-numeric:tabular-nums}.cwn-stat-rule{border-top:.5px solid var(--dsw-alias-border-l2);margin-bottom:10px}.cwn-stat-details{color:var(--dsw-alias-label-tertiary);display:grid;grid-template-columns:minmax(76px,auto) minmax(0,1fr);gap:6px 16px;margin:0}.cwn-stat-details dt,.cwn-stat-details dd{min-width:0;margin:0}.cwn-stat-details dd{color:var(--dsw-alias-label-secondary);font-variant-numeric:tabular-nums;text-align:right;overflow-wrap:anywhere}
.cwn-context-panel{width:min(264px,100vw - 24px);min-width:0;padding:12px;line-height:20px}.cwn-context-header{display:flex;align-items:center;gap:6px}.cwn-context-header strong{margin-left:auto;font-weight:500;color:var(--dsw-alias-label-primary);white-space:nowrap}.cwn-context-bar{height:4px;margin:10px 0 12px;background:var(--dsw-alias-interactive-bg-hover);border-radius:999px;corner-shape:round;overflow:hidden}.cwn-context-bar>span{display:block;height:100%;min-width:2px;background:var(--dsw-alias-label-tertiary)}.cwn-context-source{margin:0 0 8px;color:var(--dsw-alias-label-tertiary)}
.cwn .cwn-compose-model{gap:4px;padding:0 4px 0 8px;max-width:min(360px,45cqw);font-size:13px;line-height:20px}.cwn .cwn-model-effort{color:var(--dsw-alias-label-caption);flex-shrink:1000;min-width:0;overflow:hidden;text-overflow:ellipsis}.cwn-model-chevron{color:var(--dsw-alias-label-caption);transition:transform .12s}.cwn-compose-model[aria-expanded=true] .cwn-model-chevron{transform:rotate(180deg)}.cwn-model-popover button:focus-visible{outline:none;background:var(--dsw-alias-interactive-bg-hover)}
@media(prefers-reduced-motion:reduce){.cwn-progress>summary,.cwn-progress-chevron,.cwn-model-chevron{transition:none}}
`

// Deliberate user preference: soft hover transitions also on neutral/disabled controls.
export const hoverFeedbackStyles = `
.cwn button,.cwn summary,.cwn-entry,.cwn-model-popover button{transition:background-color 180ms ease,color 180ms ease,opacity 180ms ease}
.cwn button:disabled{pointer-events:auto}
.cwn button:disabled:not(.cwn-send):hover{background:var(--dsw-alias-interactive-bg-hover)!important;color:var(--dsw-alias-label-secondary)}
.cwn .cwn-send:disabled:hover{background:var(--dsw-alias-button-info-hover)!important}
@media(prefers-reduced-motion:reduce){.cwn button,.cwn summary,.cwn-entry,.cwn-model-popover button{transition:none}}
`
